export const menuData = [
  {
    category: "Starters",
    items: [
      { id: "veg-manchuria", name: "Veg Manchuria", price: 90 },
      { id: "gobi-manchuria", name: "Gobi Manchuria", price: 100 },
      { id: "crispy-corn", name: "Crispy Corn", price: 90 },
      { id: "babycorn-manchuria", name: "Baby Corn Manchuria", price: 110 },
      { id: "paneer-manchuria", name: "Paneer Manchuria", price: 130 },
      { id: "chilli-paneer", name: "Chilli Paneer", price: 130 },
      { id: "gobi-65", name: "Gobi 65", price: 130 },
      { id: "chicken-manchuria", name: "Chicken Manchuria", price: 130 },
      { id: "chilli-chicken", name: "Chilli Chicken", price: 130 },
      { id: "kaju-chicken", name: "Kaju Chicken", price: 150 },
      { id: "ginger-chicken", name: "Ginger Chicken", price: 130 },
      { id: "chicken-65", name: "Chicken 65", price: 130 },
      { id: "egg-65", name: "Egg 65", price: 110 },
      { id: "egg-manchuria", name: "Egg Manchuria", price: 110 },
      { id: "egg-chilli", name: "Egg Chilli", price: 110 },
      { id: "mushroom-manchuria", name: "Mushroom Manchuria", price: 129 },
      { id: "chicken-drum-sticks", name: "Chicken Drum Sticks", price: 180 },
      { id: "chicken-wings", name: "Chicken Wings", price: 200 },
      { id: "garlic-chicken", name: "Garlic Chicken", price: 130 },
      { id: "butter-garlic-chicken", name: "Butter Garlic Chicken", price: 140 },
      { id: "schezwan-prawns", name: "Schezwan Prawns", price: 210 },
      { id: "chilly-prawns", name: "Chilly Prawns", price: 180 },
      { id: "crispy-prawns", name: "Crispy Prawns", price: 200 },
      { id: "maggi-pakora", name: "Maggi Pakora", price: 120 },
    ],
  },
  {
    category: "Rolls",
    items: [
      { id: "veg-roll", name: "Veg Roll", price: 90 },
      { id: "veg-cheese-roll", name: "Veg Cheese Roll", price: 120 },
      { id: "egg-roll", name: "Egg Roll", price: 100 },
      { id: "paneer-roll", name: "Paneer Roll", price: 120 },
      { id: "paneer-cheese-roll", name: "Paneer Cheese Roll", price: 140 },
      { id: "chicken-roll", name: "Chicken Roll", price: 130 },
      { id: "chicken-cheese-roll", name: "Chicken Cheese Roll", price: 150 },
      { id: "egg-chicken-roll", name: "Egg Chicken Roll", price: 150 },
      { id: "mutton-keema-roll", name: "Mutton Keema Roll", price: 160 },
      { id: "double-chicken-cheese-roll", name: "Double Chicken Cheese Roll", price: 160 },
    ],
  },
  {
    category: "Breads & Puffs",
    items: [
      { id: "garlic-bread", name: "Garlic Bread", price: 70 },
      { id: "aloo-samosa", name: "Aloo Samosa (2 pieces)", price: 30 },
      { id: "veg-puff", name: "Veg Puff", price: 35 },
      { id: "egg-puff", name: "Egg Puff", price: 50 },
      { id: "chicken-puff", name: "Chicken Puff", price: 50 },
      { id: "paneer-puff", name: "Paneer Puff", price: 50 },
      { id: "potato-wedges", name: "Potato Wedges", price: 80 },
      { id: "french-fries", name: "French Fries", price: 80 },
    ],
  },
  {
    category: "Dosa",
    items: [
      { id: "rava-dosa", name: "Rava Dosa", price: 55 },
      { id: "onion-rava-dosa", name: "Onion Rava Dosa", price: 65 },
      { id: "plain-dosa", name: "Plain Dosa", price: 35 },
      { id: "masala-dosa", name: "Masala Dosa", price: 50 },
      { id: "onion-dosa", name: "Onion Dosa", price: 50 },
      { id: "onion-rava-masala-dosa", name: "Onion Rava Masala Dosa", price: 65 },
      { id: "pizza-dosa", name: "Pizza Dosa", price: 130 },
      { id: "upma-dosa", name: "Upma Dosa", price: 80 },
      { id: "jeera-dosa", name: "Jeera Dosa", price: 75 },
      { id: "butter-dosa", name: "Butter Dosa", price: 60 },
      { id: "butter-masala-dosa", name: "Butter Masala Dosa", price: 75 },
      { id: "butter-cheese-dosa", name: "Butter Cheese Dosa", price: 100 },
      { id: "butter-corn-dosa", name: "Butter Corn Dosa", price: 85 },
      { id: "butter-karam-dosa", name: "Butter Karam Dosa", price: 85 },
      { id: "double-butter-dosa", name: "Double Butter Dosa", price: 70 },
      { id: "paneer-dosa", name: "Paneer Dosa", price: 95 },
      { id: "paneer-masala-dosa", name: "Paneer Masala Dosa", price: 110 },
      { id: "chilli-paneer-dosa", name: "Chilli Paneer Dosa", price: 100 },
      { id: "paneer-schezwan-dosa", name: "Paneer Schezwan Dosa", price: 110 },
      { id: "paneer-corn-dosa", name: "Paneer Corn Dosa", price: 110 },
      { id: "masala-uttapam", name: "Masala Uttapam", price: 110 },
      { id: "onion-uttapam", name: "Onion Uttapam", price: 80 },
      { id: "kaju-dosa", name: "Kaju Dosa", price: 135 },
      { id: "butter-babycorn-dosa", name: "Butter Babycorn Dosa", price: 90 },
      { id: "spicy-babycorn-dosa", name: "Spicy Babycorn Dosa", price: 90 },
      { id: "paneer-babycorn-dosa", name: "Paneer Babycorn Dosa", price: 110 },
      { id: "cheese-babycorn-dosa", name: "Cheese Babycorn Dosa", price: 100 },
      { id: "cheese-dosa", name: "Cheese Dosa", price: 100 },
      { id: "cheese-masala-dosa", name: "Cheese Masala Dosa", price: 100 },
      { id: "double-cheese-dosa", name: "Double Cheese Dosa", price: 120 },
      { id: "cheese-schezwan-dosa", name: "Cheese Schezwan Dosa", price: 130 },
      { id: "chilli-cheese-dosa", name: "Chilli Cheese Dosa", price: 90 },
      { id: "cheese-corn-dosa", name: "Cheese Corn Dosa", price: 105 },
      { id: "spl-ghee-masala-dosa", name: "Spl Ghee Masala Dosa", price: 80 },
      { id: "ghee-karam-dosa", name: "Ghee Karam Dosa", price: 75 },
      { id: "plain-ghee-dosa", name: "Plain Ghee Dosa", price: 65 },
      { id: "plain-uttapam", name: "Plain Uttapam", price: 65 },
      { id: "butter-uttapam", name: "Butter Uttapam", price: 85 },
      { id: "cheese-uttapam", name: "Cheese Uttapam", price: 110 },
      { id: "butter-uttapam-2", name: "Butter Uttapam (listed twice)", price: 80 },
      { id: "kaju-cheese-uttapam", name: "Kaju Cheese Uttapam", price: 140 },
      { id: "paneer-uttapam", name: "Panner Uttapam", price: 110 },
      { id: "paneer-cheese-uttapam", name: "Paneer Cheese Uttapam", price: 130 },
      { id: "onion-uttapam-2", name: "Onion Uttapam", price: 80 },
    ],
  },
  {
    category: "Idli",
    items: [
      { id: "plain-idli", name: "Plain Idli (4 pieces)", price: 40 },
      { id: "butter-idli", name: "Butter Idli", price: 50 },
      { id: "plain-ghee-idli", name: "Plain Ghee Idli", price: 55 },
      { id: "karam-podi-idli", name: "Karam Podi Idli", price: 55 },
      { id: "guntur-ghee-idli", name: "Guntur Ghee Idli", price: 65 },
      { id: "sambhar-idli", name: "Sambhar Idli", price: 60 },
      { id: "paneer-schezwan-idli", name: "Paneer Schezwan Idli", price: 85 },
      { id: "cheese-schezwan-idli", name: "Cheese Schezwan Idli", price: 100 },
      { id: "idli-65", name: "Idli 65", price: 80 },
    ],
  },
  {
    category: "Fried Rice",
    items: [
      { id: "veg-fried-rice", name: "Veg Fried Rice", price: 90 },
      { id: "veg-manchurian-fried-rice", name: "Veg Manchurian Fried Rice", price: 110 },
      { id: "gobi-fried-rice", name: "Gobi Fried Rice", price: 110 },
      { id: "egg-fried-rice", name: "Egg Fried Rice", price: 110 },
      { id: "double-egg-fried-rice", name: "Double Egg Fried Rice", price: 120 },
      { id: "double-egg-dble-chicken-fried-rice", name: "Double Egg Dble Chicken Fried Rice", price: 150 },
      { id: "paneer-fried-rice", name: "Paneer Fried Rice", price: 120 },
      { id: "mixed-nonveg-fried-rice", name: "Mixed Non Veg Fried Rice", price: 180 },
      { id: "babycorn-fried-rice", name: "Babycorn Fried Rice", price: 120 },
      { id: "mushroom-fried-rice", name: "Mushroom Fried Rice", price: 120 },
      { id: "chicken-fried-rice", name: "Chicken Fried Rice", price: 130 },
      { id: "double-chicken-fried-rice", name: "Double chicken fried rice", price: 140 },
      { id: "chicken-schezwan-fried-rice", name: "Chicken Schezwan Fried Rice", price: 140 },
    ],
  },
  {
    category: "Noodles",
    items: [
      { id: "veg-noodles", name: "Veg Noodles", price: 90 },
      { id: "veg-manchurian-noodles", name: "Veg Manchurian Noodles", price: 100 },
      { id: "gobi-noodles", name: "Gobi Noodles", price: 110 },
      { id: "egg-noodles", name: "Egg Noodles", price: 110 },
      { id: "double-egg-noodles", name: "Double Egg Noodles", price: 120 },
      { id: "chicken-noodles", name: "Chicken Noodles", price: 120 },
      { id: "double-chicken-noodles", name: "Double Chicken Noodles", price: 140 },
      { id: "paneer-noodles", name: "Paneer Noodles", price: 120 },
      { id: "mushroom-noodles", name: "Mushroom Noodles", price: 120 },
      { id: "babycorn-noodles", name: "Babycorn Noodles", price: 110 },
      { id: "double-egg-dble-chicken-noodles", name: "Double Egg Dble Chicken Noodles", price: 150 },
      { id: "veg-schezwan-noodles", name: "Veg Schezwan Noodles", price: 110 },
      { id: "chicken-schezwan-noodles", name: "Chicken Schezwan Noodles", price: 130 },
    ],
  },
  {
    category: "Tea & Coffee",
    items: [
      { id: "tea", name: "Tea", price: 20 },
      { id: "filter-coffee", name: "Filter Coffee", price: 25 },
      { id: "milk", name: "Milk", price: 20 },
      { id: "black-coffee", name: "Black Coffee", price: 25 },
    ],
  },
];
